# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Prf18ccQEcySBtcKDz2BEGvtsCIU4TDu
"""

# =======================
# 4️⃣ EDA & Graphs Page
# =======================
if page == "EDA & Graphs":
    st.title("Customer Churn Dashboard - EDA")

    st.subheader("Dataset Overview")
    st.dataframe(df.head(10))

    st.subheader("Summary Statistics")
    st.write(df.describe())

    # ---------------------------
    # EDA Summary Table
    # ---------------------------
    st.subheader("EDA Summary Table")
    eda_summary = pd.DataFrame({
        "Feature": df.columns,
        "Data Type": df.dtypes,
        "Missing Values": df.isnull().sum(),
        "Unique Values": df.nunique(),
        "Mean": df.select_dtypes(include=['int64','float64']).mean().reindex(df.columns),
        "Median": df.select_dtypes(include=['int64','float64']).median().reindex(df.columns)
    })
    st.dataframe(eda_summary)

    st.subheader("Visualizations")

    # ---------------------------
    # 1️⃣ Age vs Churn
    # ---------------------------
    fig, ax = plt.subplots()
    sns.boxplot(x='churn', y='age', data=df, ax=ax)
    ax.set_title("Age vs Churn")
    st.pyplot(fig)

    # ---------------------------
    # 2️⃣ Account Tenure vs Churn
    # ---------------------------
    fig2, ax2 = plt.subplots()
    sns.histplot(data=df, x='account_tenure_months', hue='churn', bins=30, kde=True, ax=ax2)
    ax2.set_title("Account Tenure vs Churn")
    st.pyplot(fig2)

    # ---------------------------
    # 3️⃣ Churn Distribution
    # ---------------------------
    fig3, ax3 = plt.subplots()
    df['churn'].value_counts().plot(kind='bar', ax=ax3, color=['skyblue','salmon'])
    ax3.set_title("Churn Distribution")
    ax3.set_xlabel("Churn")
    ax3.set_ylabel("Count")
    st.pyplot(fig3)

    # ---------------------------
    # 4️⃣ Package Type vs Churn
    # ---------------------------
    fig4, ax4 = plt.subplots(figsize=(8,5))
    package_churn = df.groupby('package_type')['churn'].value_counts(normalize=True).unstack()
    package_churn.plot(kind='bar', stacked=True, ax=ax4, colormap='Set2')
    ax4.set_title("Churn Proportion by Package Type")
    ax4.set_xlabel("Package Type")
    ax4.set_ylabel("Proportion")
    st.pyplot(fig4)

    # ---------------------------
    # 5️⃣ Marital Status vs Churn
    # ---------------------------
    fig5, ax5 = plt.subplots(figsize=(8,5))
    marital_churn = df.groupby('marital_status')['churn'].value_counts(normalize=True).unstack()
    marital_churn.plot(kind='bar', stacked=True, ax=ax5, colormap='Pastel1')
    ax5.set_title("Churn Proportion by Marital Status")
    ax5.set_xlabel("Marital Status")
    ax5.set_ylabel("Proportion")
    st.pyplot(fig5)

    # ---------------------------
    # 6️⃣ Mobile Banking Usage vs Churn
    # ---------------------------
    fig6, ax6 = plt.subplots(figsize=(8,5))
    sns.boxplot(x='churn', y='mobile_banking_usage_pct', data=df, ax=ax6)
    ax6.set_title("Mobile Banking Usage (%) by Churn")
    st.pyplot(fig6)

    # ---------------------------
    # 7️⃣ Total Transaction Amount vs Transaction Count
    # ---------------------------
    if 'total_trans_amount_3m' in df.columns and 'total_trans_count_3m' in df.columns:
        fig7, ax7 = plt.subplots(figsize=(8,6))
        sns.scatterplot(
            data=df,
            x='total_trans_amount_3m',
            y='total_trans_count_3m',
            hue='churn',
            palette='Set1',
            alpha=0.6,
            ax=ax7
        )
        ax7.set_title("Total Transaction Amount vs Transaction Count by Churn")
        st.pyplot(fig7)

    # ---------------------------
    # 8️⃣ Correlation Heatmap
    # ---------------------------
    fig8, ax8 = plt.subplots(figsize=(12,8))
    corr_matrix = df.select_dtypes(include=['int64','float64']).corr()
    sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="coolwarm", ax=ax8)
    ax8.set_title("Correlation Heatmap of Numerical Features")
    st.pyplot(fig8)